import { APIConfig } from "@/types/api-config";

export const defaultConfigs = {
  dashboard: {
    flowInstitutionalPosition: { dolar: '', indice: '' },
    flowInstitutional30Min: { dolar: '', indice: '' },
    flowRetailPosition: { dolar: '', indice: '' },
    flowRetail30Min: { dolar: '', indice: '' },
    priceMini: { dolar: '', indice: '' },
    priceFull: { dolar: '', indice: '' },
    priceGeneral: { dolar: '', indice: '' },
  },
  flow: {
    institutionalPosition: { dolar: '', indice: '' },
    institutional30Min: { dolar: '', indice: '' },
    retailPosition: { dolar: '', indice: '' },
    retail30Min: { dolar: '', indice: '' },
    priceMini: { dolar: '', indice: '' },
    priceFull: { dolar: '', indice: '' },
    priceGeneral: { dolar: '', indice: '' },
  },
  markets: {
    usa_sp500: { dolar: '', indice: '' },
    usa_nasdaq: { dolar: '', indice: '' },
    usa_dowjones: { dolar: '', indice: '' },
    usa_vix: { dolar: '', indice: '' },
    br_usdbrl: { dolar: '', indice: '' },
    br_indfut: { dolar: '', indice: '' },
    br_brl10y: { dolar: '', indice: '' },
    eu_stoxx600: { dolar: '', indice: '' },
    eu_dax: { dolar: '', indice: '' },
    eu_ftse100: { dolar: '', indice: '' },
    com_wti: { dolar: '', indice: '' },
    com_gold: { dolar: '', indice: '' },
    com_copper: { dolar: '', indice: '' },
    dx_index: { dolar: '', indice: '' },
    dx_usdeur: { dolar: '', indice: '' },
    dx_usdjpy: { dolar: '', indice: '' },
    dx_usdgbp: { dolar: '', indice: '' },
    dx_usdcad: { dolar: '', indice: '' },
    dx_usdsek: { dolar: '', indice: '' },
    dx_usdchf: { dolar: '', indice: '' },
    em_usdbrl: { dolar: '', indice: '' },
    em_usdmxn: { dolar: '', indice: '' },
    em_usdzar: { dolar: '', indice: '' },
    em_usdcny: { dolar: '', indice: '' },
    em_usdtry: { dolar: '', indice: '' },
    em_usdinr: { dolar: '', indice: '' },
    em_usdrub: { dolar: '', indice: '' },
    em_usdhuf: { dolar: '', indice: '' },
    em_usdpln: { dolar: '', indice: '' },
    em_usdczk: { dolar: '', indice: '' },
    em_usdidr: { dolar: '', indice: '' },
    br_dif27: { dolar: '', indice: '' },
    br_dif29: { dolar: '', indice: '' },
    br_dif31: { dolar: '', indice: '' },
    br_dif33: { dolar: '', indice: '' },
    br_dif35: { dolar: '', indice: '' },
    us_2y: { dolar: '', indice: '' },
    us_10y: { dolar: '', indice: '' },
    us_30y: { dolar: '', indice: '' },
  },
  ai: {
    suggestions: { dolar: '', indice: '' },
    analysis: { dolar: '', indice: '' },
  },
};

export const marketTables = {
  usa: {
    name: "EUA",
    assets: [
      { name: "S&P 500", key: "usa_sp500" },
      { name: "NASDAQ", key: "usa_nasdaq" },
      { name: "DOW JONES", key: "usa_dowjones" },
      { name: "VIX", key: "usa_vix" },
    ],
  },
  brazil: {
    name: "Brasil",
    assets: [
      { name: "USD/BRL", key: "br_usdbrl" },
      { name: "INDFUT", key: "br_indfut" },
      { name: "BRL10Y", key: "br_brl10y" },
    ],
  },
  europe: {
    name: "Europa",
    assets: [
      { name: "STOXX 600", key: "eu_stoxx600" },
      { name: "DAX", key: "eu_dax" },
      { name: "FTSE 100", key: "eu_ftse100" },
    ],
  },
  commodities: {
    name: "Commodities",
    assets: [
      { name: "WTI OIL", key: "com_wti" },
      { name: "GOLD", key: "com_gold" },
      { name: "COPPER", key: "com_copper" },
    ],
  },
  dx: {
    name: "DX",
    assets: [
      { name: "DX", key: "dx_index" },
      { name: "USD/EUR", key: "dx_usdeur" },
      { name: "USD/JPY", key: "dx_usdjpy" },
      { name: "USD/GBP", key: "dx_usdgbp" },
      { name: "USD/CAD", key: "dx_usdcad" },
      { name: "USD/SEK", key: "dx_usdsek" },
      { name: "USD/CHF", key: "dx_usdchf" },
    ],
  },
  emergentes: {
    name: "Emergentes",
    assets: [
      { name: "USD/BRL", key: "em_usdbrl" },
      { name: "USD/MXN", key: "em_usdmxn" },
      { name: "USD/ZAR", key: "em_usdzar" },
      { name: "USD/CNY", key: "em_usdcny" },
      { name: "USD/TRY", key: "em_usdtry" },
      { name: "USD/INR", key: "em_usdinr" },
      { name: "USD/RUB", key: "em_usdrub" },
      { name: "USD/HUF", key: "em_usdhuf" },
      { name: "USD/PLN", key: "em_usdpln" },
      { name: "USD/CZK", key: "em_usdczk" },
      { name: "USD/IDR", key: "em_usdidr" },
    ],
  },
  jurosbr: {
    name: "Juros BR",
    assets: [
      { name: "DIF27", key: "br_dif27" },
      { name: "DIF29", key: "br_dif29" },
      { name: "DIF31", key: "br_dif31" },
      { name: "DIF33", key: "br_dif33" },
      { name: "DIF35", key: "br_dif35" },
    ],
  },
  juroseua: {
    name: "Juros EUA",
    assets: [
      { name: "US2Y", key: "us_2y" },
      { name: "US10Y", key: "us_10y" },
      { name: "US30Y", key: "us_30y" },
    ],
  },
};

export const sectionFields = {
  dashboard: {
    flowInstitutionalPosition: "Fluxo Institucional - Posição",
    flowInstitutional30Min: "Fluxo Institucional - 30 minutos",
    flowRetailPosition: "Fluxo Varejo - Posição",
    flowRetail30Min: "Fluxo Varejo - 30 minutos",
    priceMini: "Preço Médio - Mini",
    priceFull: "Preço Médio - Cheio",
    priceGeneral: "Preço Médio - Geral",
  },
  flow: {
    institutionalPosition: "Fluxo Institucional - Posição",
    institutional30Min: "Fluxo Institucional - 30 minutos",
    retailPosition: "Fluxo Varejo - Posição",
    retail30Min: "Fluxo Varejo - 30 minutos",
    priceMini: "Preço Médio - Mini",
    priceFull: "Preço Médio - Cheio",
    priceGeneral: "Preço Médio - Geral",
  },
  markets: marketTables,
  ai: {
    suggestions: "Sugestões",
    analysis: "Análise de Mercado",
  },
};
